name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in your repo secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in your repo secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: warunakith/mint-test/mint-test-image:latest  # Change to your image name

