name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to <Registry Name>
        uses: docker/login-action@v3  # Use the latest version
        with:
          registry: <registry-endpoint>
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: warunakith/mint-test/mint-test-image:latest  # Change to your image name
