name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to <Registry Name>
        uses: docker/login-action@v3  # Use the latest version
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: warunakith/mint-test-image:latest  # Change to your image name

      - name: Deploy via SSH (Password Auth)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull warunakith/mint-test-image:latest
            docker stop mint-test || true
            docker rm mint-test || true
            docker run -d --name mint-test --network my_network --log-driver=json-file --log-opt tag="mintapp" -p 8000:8000 warunakith/mint-test-image:latest
            

